[package]
name    = "kbhero-daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "keyboardhero"
path = "src/main.rs"

[dependencies]
kbhero-core = { workspace = true }
tokio       = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
kbhero-linux = { path = "../kbhero-linux" }
atspi        = { version = "0.30", features = ["tokio"] }
zbus         = { version = "5", features = ["tokio"], default-features = false }
futures-lite = "2"

[target.'cfg(target_os = "windows")'.dependencies]
kbhero-windows = { path = "../kbhero-windows" }

[target.'cfg(target_os = "macos")'.dependencies]
kbhero-macos = { path = "../kbhero-macos" }
